spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bibliographic?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always